import { fireEvent, render, screen } from "@testing-library/react"
import { describe, expect, it, vi } from "vitest"
import { CheckpointPanel } from "./CheckpointPanel"
import { checkpointFixture } from "../test/fixtures"

it("shows complete read-only checkpoint state and can locate its trigger event", () => {
  const onLocate = vi.fn()
  render(<CheckpointPanel checkpoint={checkpointFixture} onClose={() => undefined} onLocate={onLocate} />)
  expect(screen.getByText(/Day 1/)).toBeVisible()
  expect(screen.getByText("Drunk")).toBeVisible()
  expect(screen.getByText("Poisoner")).toBeVisible()
  expect(screen.getByText("Perceived identity: Librarian")).toBeVisible()
  expect(screen.getByText("Known alignment: good")).toBeVisible()
  expect(screen.getByText("Dead vote: available")).toBeVisible()
  expect(screen.getByText(/You start knowing that one of two players/)).toBeVisible()
  expect(screen.getByText("Reminders: is drunk")).toBeVisible()
  expect(screen.getByText("Pending: request_private_chat")).toBeVisible()
  expect(screen.getByText("Triggers: claim.public")).toBeVisible()
  fireEvent.change(screen.getByLabelText("Player notebook"), { target: { value: "bob" } })
  expect(screen.getByText("Alice is probing me.")).toBeVisible()
  expect(screen.getByText("Actual role: Poisoner")).toBeVisible()
  expect(screen.getByText("Perceived identity: Poisoner")).toBeVisible()
  expect(screen.getByText("Alignment: evil")).toBeVisible()
  expect(screen.getByText("Known alignment: evil")).toBeVisible()
  expect(screen.getByText("Life: dead")).toBeVisible()
  expect(screen.getByText("Dead vote: spent")).toBeVisible()
  expect(screen.getByText(/Each night, choose a player/)).toBeVisible()
  expect(screen.getByText("Reminders: poisoned, dead vote spent")).toBeVisible()
  expect(screen.getByText("Pending: nominate")).toBeVisible()
  expect(screen.getByText("Triggers: vote.cast")).toBeVisible()
  expect(screen.getByText(/private-chat-17-1/)).toBeVisible()
  expect(screen.getByText(/protected_player_id/)).toBeVisible()
  expect(screen.queryByRole("button", { name: /restore|resume|edit|export/i })).toBeNull()
  fireEvent.click(screen.getByRole("button", { name: /locate event 7/i }))
  expect(onLocate).toHaveBeenCalledWith(7)
})
